[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "python3-venv"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python3 app.py"