[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "python3-venv"]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", ". /opt/venv/bin/activate", "python3 -m pip install --upgrade pip", "cd backend/scrapers && python3 -m pip install -r ../../requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python3 app.py"