[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y python3 python3-pip python3-dev && \
pip3 install --upgrade pip && \
pip3 install -r requirements.txt && \
npm install
"""

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"
PORT = "3000"