[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y python3-pip && \
pip3 install --upgrade pip && \
pip3 install -r requirements.txt && \
npm install
"""

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
healthcheckInterval = 10

[deploy.envs]
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"