[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[build]
cmd = """
pip3 install -r requirements.txt && \
npm install
"""

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 30