[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y python3 python3-pip python3-dev && \
pip3 install --no-cache-dir -r requirements.txt && \
npm install
"""

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"