[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -m flask run --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[[deploy.envs]]
key = "NIXPACKS_PYTHON_VERSION"
value = "3.10"

[[deploy.envs]]
key = "PYTHONUNBUFFERED"
value = "1"